name: Artifacts
on: push
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: date > date.txt
      - uses: actions/upload-artifact@v4
        with:
          name: uploaded # Name of the artifact
          path: date.txt # upload file name
          retention-days: 1 # Number of days to keep the artifact
  downlad:
    runs-on: ubuntu-latest
    needs: [upload]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: uploaded # Name of the artifact to download
          path: downloaded # Directory to download the artifact to
      - run: cat downloaded/date.txt
