name: Release go
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # v1.2.3のようなタグがpushされたとき
jobs:
  release-go:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }} # タグ名を取得
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: |
          go build -ldflags "-X main.version=${VERSION}" -o "${RUNNER_TEMP}/auto-release-sample" go/auto-release-sample/main.go
      - name: Create release note and upload asset
        run: |
          gh release create "${VERSION}" --title "${VERSION}" --generate-notes 
          gh release upload "${VERSION}" "${RUNNER_TEMP}/auto-release-sample"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
