name: Static analysis
on:
  push:
  pull_request:
    paths: ['.github/workflows/*.yml', '.github/workflows/*.yaml']
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Commit changes to cancel the current job
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install actionlint
        run: |
          curl -sSL https://github.com/rhysd/actionlint/releases/download/v1.7.1/actionlint_linux_amd64.tar.gz | tar -xz -C /usr/local/bin
      - name: Run Actionlint
        run: actionlint
